import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useData } from '../../context/DataContext'
import { Icon } from '../../components/ui/Icons'
import { DiffView } from '../../components/ui/DiffView'
import { Card, Confidence, EmptyState, PageHeader, SeverityBadge, StatusBadge } from '../../components/ui/Elements'

export function FindingDetailPage() {
  const { id } = useParams()
  const { getFinding, getProject, setFindingStatus, applyFix } = useData()
  const navigate = useNavigate()
  const [copied, setCopied] = useState(false)
  const [verifying, setVerifying] = useState(false)
  const [fixError, setFixError] = useState('')
  const f = getFinding(id)

  if (!f) {
    return (
      <Card>
        <EmptyState icon="alert" title="Finding not found" action={<Link to="/findings" className="btn btn-primary">Back to findings</Link>}>
          It may belong to a scan that was removed.
        </EmptyState>
      </Card>
    )
  }

  const project = getProject(f.projectId)

  const applyAndVerify = async () => {
    setVerifying(true)
    setFixError('')
    try {
      await applyFix(f.id)
      navigate(`/findings/${f.id}/verification`)
    } catch (err) {
      setFixError(err.message)
    } finally {
      setVerifying(false)
    }
  }

  const copyPatch = async () => {
    try {
      await navigator.clipboard.writeText(f.after.join('\n'))
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      // clipboard blocked
    }
  }

  return (
    <>
      <PageHeader
        back={{ to: '/findings', label: 'Findings' }}
        eyebrow={`${f.id} · ${project?.name || f.projectId}`}
        title={f.title}
        subtitle={<span className="mono">{f.file}:{f.line}</span>}
        actions={
          <>
            {f.status !== 'false_positive' ? (
              <button className="btn btn-outline" onClick={() => setFindingStatus(f.id, 'false_positive')}>Mark false positive</button>
            ) : (
              <button className="btn btn-outline" onClick={() => setFindingStatus(f.id, 'open')}>Reopen</button>
            )}
            {f.verification && (
              <Link to={`/findings/${f.id}/verification`} className="btn btn-outline"><Icon name="checkCircle" size={16} /> Verification</Link>
            )}
          </>
        }
      />

      <div className="meta-strip">
        <div><span>Severity</span><SeverityBadge severity={f.severity} /></div>
        <div><span>Status</span><StatusBadge status={f.status} /></div>
        <div><span>CWE</span><a href={`https://cwe.mitre.org/data/definitions/${f.cwe.replace('CWE-', '')}.html`} target="_blank" rel="noreferrer" className="tag">{f.cwe}</a></div>
        <div><span>OWASP</span><strong>{f.owasp}</strong></div>
        <div><span>AI confidence</span><Confidence value={f.confidence} /></div>
      </div>

      <div className="grid-2">
        <Card title="What's wrong">
          <p>{f.explanation}</p>
          <p className="small muted">{f.cwe}: {f.cweName}</p>
        </Card>
        <Card title="Attack scenario" className="attack-card">
          <div className="attack">
            <Icon name="alert" size={20} />
            <p>{f.attack}</p>
          </div>
        </Card>
      </div>

      <Card
        title={<><Icon name="sparkles" size={18} /> AI-suggested fix</>}
        action={
          <div className="row-gap">
            <button className="btn btn-sm btn-ghost" onClick={copyPatch}>{copied ? 'Copied' : 'Copy patch'}</button>
            <button className="btn btn-sm btn-primary" onClick={applyAndVerify} disabled={verifying || f.status === 'false_positive'}>
              {verifying ? <><span className="spinner light" /> Verifying…</> : <><Icon name="checkCircle" size={14} /> Apply & verify</>}
            </button>
          </div>
        }
      >
        {fixError && <div className="alert alert-info" role="status">{fixError}</div>}
        <DiffView before={f.before} after={f.after} file={f.file} />
        <p className="small muted fix-note">Generated by Gemini. Review the change before merging. Verification re-runs rule <code>{f.rule}</code> on the patched file.</p>
      </Card>

      <Card title="Detection details">
        <dl className="details">
          <dt>Semgrep rule</dt><dd className="mono">{f.rule}</dd>
          <dt>Location</dt><dd className="mono">{f.file}, line {f.line}</dd>
          <dt>Language</dt><dd>{f.language}</dd>
          <dt>Project</dt><dd>{project?.name}</dd>
        </dl>
      </Card>
    </>
  )
}
